### ISSUE TITLE
missing file

### ISSUE THREAD

**Issue by TheTesla** [scott89/caffe-fcnt#1]
The hdf5.h included in /home/willi/FCNT/caffe-fcnt/include/caffe/util/io.hpp is missing.

**Comment by scott89** [comment]
Hi! Please try to install libhdf5 first. If you are using Ubuntu, you can simply use the command  
`sudo apt-get install libhdf5-serial-dev`

**Comment by xiaotian3** [comment]
您好，问下源代码中的caffe-fcnt是如何编译的？只有在linux环境下才行么？还有比较详细的配置过程么

**Comment by scott89** [comment]
caffe-fcnt的编译方法与caffe相同，目前只在Linux系统上进行过测试，详细的编译过程参见caffe官网

**Comment by xiaotian3** [comment]
能看看您的caffe-fcnt中makefile文件是如何配置的吗？我配置 的过程中总是出现问题，我的linux系统之前配置过caffe ,不知道有没有影响。
